#Agent database with memory - no vectorization#

from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain_deepseek import ChatDeepSeek
from langchain.tools import tool
from pydantic import BaseModel,Field
import os

#environment variables
load_dotenv()

URI = os.getenv("URI_DATABASE_NEO4J")
USERNAME = os.getenv("USERNAME_NEO4J")
PASSWORD = os.getenv("PASSWORD_NEO4J")
DATABASE = os.getenv("DATABASE_NEO4J")

#Neo4j Database connection details
from neo4j import GraphDatabase
from langchain_neo4j import GraphCypherQAChain, Neo4jGraph

AUTH = (USERNAME, PASSWORD)

#DeepSeek Model Configuration
model = ChatDeepSeek(model="deepseek-chat", temperature=0.1)

@tool("verify_neo4j_connection", description="Tool to verify connection to neo4j database")
def verify_neo4j_connection():
    """Tool responsible to verify the connection to neo4j database, this tool will be used in the agent's workflow to check if the 
    connection to the database is successful or not"""
    with GraphDatabase.driver(URI, auth=AUTH) as driver:
        try:
            driver.verify_connectivity()
            return "Connected to Neo4j successfully!"
        except Exception as e:
            return f"Connection failed: {str(e)}"


@tool("get_neo4j_database_schema", description="Tool to get the schema of the neo4j database")
def get_neo4j_database_schema() -> str:
    """"Tool responsible to get the enchanced schema of Neo4j database. The agent will use this tool to have a better understanding of the database structure and the relationships between the entities in the database, this will help the agent to generate more accurate cypher queries based on the user's question and the database schema."""
    try:
        graph = Neo4jGraph(url=URI, username=USERNAME, password=PASSWORD, database=DATABASE, enhanced_schema=True)
        schema = graph.schema
        result = schema
        
        return result
    
    except Exception as e:
        return f"Failed to get database schema: {str(e)}"


@tool("transformer_human_answer_to_cypher_query", description="Tool to transform human question into cypher query")
def build_cypher_query_from_human_question(question: str) -> str:
    """Tool responsible to transform the human question into a cypher query that can be executed on the neo4j database. This tool result will be used in the execute_cypher_query_on_neo4j_database tool to execute the generated cypher query on the neo4j database and return the results of the query execution."""
    with Neo4jGraph(url=URI, username=USERNAME, password=PASSWORD, database=DATABASE, enhanced_schema=True) as graph:
        chain = GraphCypherQAChain.from_llm(ChatDeepSeek(model='deepseek-chat', temperature = 0.4), graph=graph, verbose=True, allow_dangerous_requests=True)
        result = chain.invoke(question)
        return result

@tool("execute_cypher_query_on_neo4j_database", description="Tool to execute cypher query on neo4j database, it can be create, update or delete query")
def execute_cypher_query_on_neo4j_database(cypher_query: str) -> str:
    """Tool responsible to execute the cypher query generated by the agent on the neo4j database and return the results of the query execution."""
    
    with Neo4jGraph(url=URI, username=USERNAME, password=PASSWORD, enhanced_schema=True, database=DATABASE) as graph:
        try:
            result = graph.query(cypher_query)
            return result
        except Exception as e:
            return f"Failed to execute cypher query: {str(e)}"

class Neo4jQueryOutput(BaseModel):
    query_result: str = Field(description="Result of the query execution on neo4j database, return in a human readable format")




if __name__ == "__main__":
    user_question = input("Enter your chat about neo4j database: ")
    agent = create_agent(
        model=model,
        tools=[verify_neo4j_connection, get_neo4j_database_schema, build_cypher_query_from_human_question,execute_cypher_query_on_neo4j_database],
        system_prompt=f"""You are an assistant responsible for connecting to a neo4j database, understanding its schema, interpreting the user's question, generating and executing cypher queries, and returning results. The user question is: {user_question}

        Follow these steps strictly in order:

        1. VERIFY CONNECTION: Always start by calling 'verify_neo4j_connection' to confirm the database is reachable.

        2. GET SCHEMA: Call 'get_neo4j_database_schema' to retrieve and understand the database structure before doing anything else.

        3. EXECUTE QUERY based on the operation type:
        - If the user's question requires only READ operations (MATCH, RETURN, etc.), use the tool 'transformer_human_answer_to_cypher_query' to build and run the query.
        - If the user's question requires WRITE operations (CREATE, UPDATE/SET, DELETE, MERGE that modifies data), use the tool 'execute_cypher_query_on_neo4j_database' directly with the appropriate cypher query.

        4. FINALIZE:
        - If a CREATE, UPDATE, or DELETE operation was performed: call 'get_neo4j_database_schema' once more to validate the changes, then stop immediately — do NOT call any more tools.
        - If only a READ operation was performed: return the results and stop — do NOT call any more tools.""",
                response_format=Neo4jQueryOutput,
    )
    
    result = agent.invoke({"messages":[{"role":"user","content": user_question}]})
    print(result["structured_response"].query_result)